// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (workspace_id, email, role, token, invited_by, expires_at)
VALUES ($1, $2, $3::user_role, $4, $5, $6)
RETURNING id, workspace_id, email, role, token, invited_by, expires_at, accepted_at, accepted_by, created_at
`

type CreateInvitationParams struct {
	WorkspaceID string    `json:"workspace_id"`
	Email       string    `json:"email"`
	Role        UserRole  `json:"role"`
	Token       string    `json:"token"`
	InvitedBy   string    `json:"invited_by"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = $1 AND workspace_id = $2
`

type DeleteInvitationParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) error {
	_, err := q.db.Exec(ctx, deleteInvitation, arg.ID, arg.WorkspaceID)
	return err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, workspace_id, email, role, token, invited_by, expires_at, accepted_at, accepted_by, created_at FROM invitations WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitationsByWorkspace = `-- name: ListInvitationsByWorkspace :many
SELECT id, workspace_id, email, role, token, invited_by, expires_at, accepted_at, accepted_by, created_at FROM invitations
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvitationsByWorkspace(ctx context.Context, workspaceID string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.Token,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :one
UPDATE invitations
SET accepted_at = NOW(),
    accepted_by = $1
WHERE id = $2
  AND accepted_at IS NULL
RETURNING id, workspace_id, email, role, token, invited_by, expires_at, accepted_at, accepted_by, created_at
`

type MarkInvitationAcceptedParams struct {
	AcceptedBy pgtype.UUID `json:"accepted_by"`
	ID         string      `json:"id"`
}

func (q *Queries) MarkInvitationAccepted(ctx context.Context, arg MarkInvitationAcceptedParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, markInvitationAccepted, arg.AcceptedBy, arg.ID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.CreatedAt,
	)
	return i, err
}
