// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const countMonitoringProfiles = `-- name: CountMonitoringProfiles :one
SELECT COUNT(*)::int as count FROM monitoring_profiles
WHERE workspace_id = $1
`

func (q *Queries) CountMonitoringProfiles(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countMonitoringProfiles, workspaceID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createMonitoringProfile = `-- name: CreateMonitoringProfile :one
INSERT INTO monitoring_profiles (workspace_id, name, description, is_active, status, deployed_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, name, description, is_active, created_at, updated_at, status, last_run_at, last_run_mentions, total_mentions, deployed_by, deployed_at
`

type CreateMonitoringProfileParams struct {
	WorkspaceID string      `json:"workspace_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	IsActive    bool        `json:"is_active"`
	Status      string      `json:"status"`
	DeployedBy  pgtype.UUID `json:"deployed_by"`
}

func (q *Queries) CreateMonitoringProfile(ctx context.Context, arg CreateMonitoringProfileParams) (MonitoringProfile, error) {
	row := q.db.QueryRow(ctx, createMonitoringProfile,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.Status,
		arg.DeployedBy,
	)
	var i MonitoringProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LastRunAt,
		&i.LastRunMentions,
		&i.TotalMentions,
		&i.DeployedBy,
		&i.DeployedAt,
	)
	return i, err
}

const createPainPointEmbedding = `-- name: CreatePainPointEmbedding :one

INSERT INTO pain_point_embeddings (profile_id, workspace_id, phrase, embedding)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, workspace_id, phrase, embedding, created_at
`

type CreatePainPointEmbeddingParams struct {
	ProfileID   string              `json:"profile_id"`
	WorkspaceID string              `json:"workspace_id"`
	Phrase      string              `json:"phrase"`
	Embedding   *pgvector_go.Vector `json:"embedding"`
}

// ─── Pain-Point Embeddings ─────────────────────────────
func (q *Queries) CreatePainPointEmbedding(ctx context.Context, arg CreatePainPointEmbeddingParams) (PainPointEmbedding, error) {
	row := q.db.QueryRow(ctx, createPainPointEmbedding,
		arg.ProfileID,
		arg.WorkspaceID,
		arg.Phrase,
		arg.Embedding,
	)
	var i PainPointEmbedding
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.WorkspaceID,
		&i.Phrase,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonitoringProfile = `-- name: DeleteMonitoringProfile :exec
DELETE FROM monitoring_profiles
WHERE id = $1 AND workspace_id = $2
`

type DeleteMonitoringProfileParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteMonitoringProfile(ctx context.Context, arg DeleteMonitoringProfileParams) error {
	_, err := q.db.Exec(ctx, deleteMonitoringProfile, arg.ID, arg.WorkspaceID)
	return err
}

const deletePainPointEmbeddingsByProfile = `-- name: DeletePainPointEmbeddingsByProfile :exec
DELETE FROM pain_point_embeddings
WHERE profile_id = $1
`

func (q *Queries) DeletePainPointEmbeddingsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.Exec(ctx, deletePainPointEmbeddingsByProfile, profileID)
	return err
}

const findSimilarPainPoints = `-- name: FindSimilarPainPoints :many
SELECT ppe.id, ppe.profile_id, ppe.workspace_id, ppe.phrase,
    (1 - (ppe.embedding <=> $1::vector))::float8 as similarity
FROM pain_point_embeddings ppe
JOIN monitoring_profiles mp ON mp.id = ppe.profile_id
WHERE ppe.workspace_id = $2 AND mp.is_active = true
ORDER BY ppe.embedding <=> $1::vector
LIMIT $3
`

type FindSimilarPainPointsParams struct {
	QueryEmbedding *pgvector_go.Vector `json:"query_embedding"`
	WorkspaceID    string              `json:"workspace_id"`
	Lim            int32               `json:"lim"`
}

type FindSimilarPainPointsRow struct {
	ID          string  `json:"id"`
	ProfileID   string  `json:"profile_id"`
	WorkspaceID string  `json:"workspace_id"`
	Phrase      string  `json:"phrase"`
	Similarity  float64 `json:"similarity"`
}

// Only match pain points from ACTIVE monitoring profiles so deactivating a
// profile actually stops its phrases from scoring new mentions.
func (q *Queries) FindSimilarPainPoints(ctx context.Context, arg FindSimilarPainPointsParams) ([]FindSimilarPainPointsRow, error) {
	rows, err := q.db.Query(ctx, findSimilarPainPoints, arg.QueryEmbedding, arg.WorkspaceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindSimilarPainPointsRow{}
	for rows.Next() {
		var i FindSimilarPainPointsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Phrase,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentStats = `-- name: GetAgentStats :one
SELECT
  COUNT(DISTINCT m.id)::int AS mentions,
  COUNT(DISTINCT r.id)::int AS replies,
  COUNT(DISTINCT r.id) FILTER (WHERE r.status = 'posted')::int AS replies_posted,
  COUNT(DISTINCT l.id)::int AS leads,
  COUNT(DISTINCT l.id) FILTER (WHERE l.stage = 'converted')::int AS leads_converted
FROM monitoring_profiles mp
LEFT JOIN keywords k ON k.profile_id = mp.id
LEFT JOIN mentions m ON m.keyword_id = k.id AND m.created_at >= $1
LEFT JOIN replies r ON r.mention_id = m.id
LEFT JOIN leads l ON l.mention_id = m.id
WHERE mp.id = $2 AND mp.workspace_id = $3
`

type GetAgentStatsParams struct {
	Since       time.Time `json:"since"`
	ProfileID   string    `json:"profile_id"`
	WorkspaceID string    `json:"workspace_id"`
}

type GetAgentStatsRow struct {
	Mentions       int32 `json:"mentions"`
	Replies        int32 `json:"replies"`
	RepliesPosted  int32 `json:"replies_posted"`
	Leads          int32 `json:"leads"`
	LeadsConverted int32 `json:"leads_converted"`
}

// Aggregated stats for a single agent over a rolling window. The mentions
// join goes via keywords.profile_id so deletions stay consistent.
func (q *Queries) GetAgentStats(ctx context.Context, arg GetAgentStatsParams) (GetAgentStatsRow, error) {
	row := q.db.QueryRow(ctx, getAgentStats, arg.Since, arg.ProfileID, arg.WorkspaceID)
	var i GetAgentStatsRow
	err := row.Scan(
		&i.Mentions,
		&i.Replies,
		&i.RepliesPosted,
		&i.Leads,
		&i.LeadsConverted,
	)
	return i, err
}

const getMonitoringProfile = `-- name: GetMonitoringProfile :one
SELECT id, workspace_id, name, description, is_active, created_at, updated_at, status, last_run_at, last_run_mentions, total_mentions, deployed_by, deployed_at FROM monitoring_profiles
WHERE id = $1 AND workspace_id = $2
`

type GetMonitoringProfileParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) GetMonitoringProfile(ctx context.Context, arg GetMonitoringProfileParams) (MonitoringProfile, error) {
	row := q.db.QueryRow(ctx, getMonitoringProfile, arg.ID, arg.WorkspaceID)
	var i MonitoringProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LastRunAt,
		&i.LastRunMentions,
		&i.TotalMentions,
		&i.DeployedBy,
		&i.DeployedAt,
	)
	return i, err
}

const listActiveMonitoringProfiles = `-- name: ListActiveMonitoringProfiles :many
SELECT id, workspace_id, name, description, is_active, created_at, updated_at, status, last_run_at, last_run_mentions, total_mentions, deployed_by, deployed_at FROM monitoring_profiles
WHERE workspace_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveMonitoringProfiles(ctx context.Context, workspaceID string) ([]MonitoringProfile, error) {
	rows, err := q.db.Query(ctx, listActiveMonitoringProfiles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringProfile{}
	for rows.Next() {
		var i MonitoringProfile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.LastRunAt,
			&i.LastRunMentions,
			&i.TotalMentions,
			&i.DeployedBy,
			&i.DeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT mp.id, mp.workspace_id, mp.name, mp.description, mp.is_active,
       mp.status, mp.last_run_at, mp.last_run_mentions, mp.total_mentions,
       mp.deployed_by, mp.deployed_at, mp.created_at, mp.updated_at,
       (SELECT COUNT(*)::int FROM keywords k WHERE k.profile_id = mp.id) AS keyword_count,
       (SELECT COUNT(*)::int FROM pain_point_embeddings ppe WHERE ppe.profile_id = mp.id) AS pain_point_count
FROM monitoring_profiles mp
WHERE mp.workspace_id = $1
ORDER BY mp.created_at DESC
`

type ListAgentsRow struct {
	ID              string             `json:"id"`
	WorkspaceID     string             `json:"workspace_id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	IsActive        bool               `json:"is_active"`
	Status          string             `json:"status"`
	LastRunAt       pgtype.Timestamptz `json:"last_run_at"`
	LastRunMentions pgtype.Int4        `json:"last_run_mentions"`
	TotalMentions   int32              `json:"total_mentions"`
	DeployedBy      pgtype.UUID        `json:"deployed_by"`
	DeployedAt      pgtype.Timestamptz `json:"deployed_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	KeywordCount    int32              `json:"keyword_count"`
	PainPointCount  int32              `json:"pain_point_count"`
}

// Lists every agent (monitoring profile) for a workspace with roll-up stats:
// keyword count, pain-point count, mention count, reply count. This drives
// the /agents dashboard cards.
func (q *Queries) ListAgents(ctx context.Context, workspaceID string) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentsRow{}
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.Status,
			&i.LastRunAt,
			&i.LastRunMentions,
			&i.TotalMentions,
			&i.DeployedBy,
			&i.DeployedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KeywordCount,
			&i.PainPointCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveProfiles = `-- name: ListAllActiveProfiles :many
SELECT id, workspace_id, name, description, is_active, created_at, updated_at, status, last_run_at, last_run_mentions, total_mentions, deployed_by, deployed_at FROM monitoring_profiles
WHERE is_active = true
ORDER BY workspace_id, created_at DESC
`

func (q *Queries) ListAllActiveProfiles(ctx context.Context) ([]MonitoringProfile, error) {
	rows, err := q.db.Query(ctx, listAllActiveProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringProfile{}
	for rows.Next() {
		var i MonitoringProfile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.LastRunAt,
			&i.LastRunMentions,
			&i.TotalMentions,
			&i.DeployedBy,
			&i.DeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoringProfiles = `-- name: ListMonitoringProfiles :many
SELECT id, workspace_id, name, description, is_active, created_at, updated_at, status, last_run_at, last_run_mentions, total_mentions, deployed_by, deployed_at FROM monitoring_profiles
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMonitoringProfiles(ctx context.Context, workspaceID string) ([]MonitoringProfile, error) {
	rows, err := q.db.Query(ctx, listMonitoringProfiles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoringProfile{}
	for rows.Next() {
		var i MonitoringProfile
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.LastRunAt,
			&i.LastRunMentions,
			&i.TotalMentions,
			&i.DeployedBy,
			&i.DeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPainPointEmbeddings = `-- name: ListPainPointEmbeddings :many
SELECT id, profile_id, workspace_id, phrase, embedding, created_at FROM pain_point_embeddings
WHERE profile_id = $1
ORDER BY created_at
`

func (q *Queries) ListPainPointEmbeddings(ctx context.Context, profileID string) ([]PainPointEmbedding, error) {
	rows, err := q.db.Query(ctx, listPainPointEmbeddings, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PainPointEmbedding{}
	for rows.Next() {
		var i PainPointEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Phrase,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPainPointEmbeddingsByWorkspace = `-- name: ListPainPointEmbeddingsByWorkspace :many
SELECT id, profile_id, workspace_id, phrase, embedding, created_at FROM pain_point_embeddings
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListPainPointEmbeddingsByWorkspace(ctx context.Context, workspaceID string) ([]PainPointEmbedding, error) {
	rows, err := q.db.Query(ctx, listPainPointEmbeddingsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PainPointEmbedding{}
	for rows.Next() {
		var i PainPointEmbedding
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.WorkspaceID,
			&i.Phrase,
			&i.Embedding,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAgentRun = `-- name: TouchAgentRun :one
UPDATE monitoring_profiles
SET last_run_at = NOW(),
    last_run_mentions = $1,
    total_mentions = total_mentions + $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, workspace_id, name, description, is_active, created_at, updated_at, status, last_run_at, last_run_mentions, total_mentions, deployed_by, deployed_at
`

type TouchAgentRunParams struct {
	LastRunMentions pgtype.Int4 `json:"last_run_mentions"`
	ID              string      `json:"id"`
}

// Called by the monitor after each scan to record last-run telemetry.
func (q *Queries) TouchAgentRun(ctx context.Context, arg TouchAgentRunParams) (MonitoringProfile, error) {
	row := q.db.QueryRow(ctx, touchAgentRun, arg.LastRunMentions, arg.ID)
	var i MonitoringProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LastRunAt,
		&i.LastRunMentions,
		&i.TotalMentions,
		&i.DeployedBy,
		&i.DeployedAt,
	)
	return i, err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :one
UPDATE monitoring_profiles
SET status = $1, is_active = ($1 = 'active'), updated_at = NOW()
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, name, description, is_active, created_at, updated_at, status, last_run_at, last_run_mentions, total_mentions, deployed_by, deployed_at
`

type UpdateAgentStatusParams struct {
	Status      string `json:"status"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

// Toggles an agent between active/paused without touching its config.
func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (MonitoringProfile, error) {
	row := q.db.QueryRow(ctx, updateAgentStatus, arg.Status, arg.ID, arg.WorkspaceID)
	var i MonitoringProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LastRunAt,
		&i.LastRunMentions,
		&i.TotalMentions,
		&i.DeployedBy,
		&i.DeployedAt,
	)
	return i, err
}

const updateMonitoringProfile = `-- name: UpdateMonitoringProfile :one
UPDATE monitoring_profiles
SET name = $1, description = $2, is_active = $3, status = $4, updated_at = NOW()
WHERE id = $5 AND workspace_id = $6
RETURNING id, workspace_id, name, description, is_active, created_at, updated_at, status, last_run_at, last_run_mentions, total_mentions, deployed_by, deployed_at
`

type UpdateMonitoringProfileParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
	Status      string `json:"status"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) UpdateMonitoringProfile(ctx context.Context, arg UpdateMonitoringProfileParams) (MonitoringProfile, error) {
	row := q.db.QueryRow(ctx, updateMonitoringProfile,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
	)
	var i MonitoringProfile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.LastRunAt,
		&i.LastRunMentions,
		&i.TotalMentions,
		&i.DeployedBy,
		&i.DeployedAt,
	)
	return i, err
}
