// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeWorkspaceSetup = `-- name: CompleteWorkspaceSetup :one
UPDATE workspaces
SET setup_completed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, clerk_org_id, name, slug, tier, stripe_customer_id, settings, keyword_limit, mention_limit, seat_limit, created_at, updated_at, setup_completed_at
`

func (q *Queries) CompleteWorkspaceSetup(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, completeWorkspaceSetup, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Name,
		&i.Slug,
		&i.Tier,
		&i.StripeCustomerID,
		&i.Settings,
		&i.KeywordLimit,
		&i.MentionLimit,
		&i.SeatLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SetupCompletedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (clerk_user_id, workspace_id, email, name, avatar_url, role, password_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, clerk_user_id, workspace_id, email, name, avatar_url, role, is_active, last_active_at, created_at, updated_at, password_hash
`

type CreateUserParams struct {
	ClerkUserID  string      `json:"clerk_user_id"`
	WorkspaceID  string      `json:"workspace_id"`
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	Role         UserRole    `json:"role"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ClerkUserID,
		arg.WorkspaceID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.Role,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active = false, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING id, clerk_user_id, workspace_id, email, name, avatar_url, role, is_active, last_active_at, created_at, updated_at, password_hash
`

type DeactivateUserParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, deactivateUser, arg.ID, arg.WorkspaceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, clerk_user_id, workspace_id, email, name, avatar_url, role, is_active, last_active_at, created_at, updated_at, password_hash FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, clerk_user_id, workspace_id, email, name, avatar_url, role, is_active, last_active_at, created_at, updated_at, password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listUsersByExternalID = `-- name: ListUsersByExternalID :many
SELECT id, clerk_user_id, workspace_id, email, name, avatar_url, role, is_active, last_active_at, created_at, updated_at, password_hash FROM users
WHERE clerk_user_id = $1
`

func (q *Queries) ListUsersByExternalID(ctx context.Context, clerkUserID string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByExternalID, clerkUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ClerkUserID,
			&i.WorkspaceID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
			&i.IsActive,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByWorkspace = `-- name: ListUsersByWorkspace :many
SELECT id, clerk_user_id, workspace_id, email, name, avatar_url, role, is_active, last_active_at, created_at, updated_at, password_hash FROM users
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListUsersByWorkspace(ctx context.Context, workspaceID string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ClerkUserID,
			&i.WorkspaceID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
			&i.IsActive,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $1::user_role, updated_at = NOW()
WHERE id = $2 AND workspace_id = $3
RETURNING id, clerk_user_id, workspace_id, email, name, avatar_url, role, is_active, last_active_at, created_at, updated_at, password_hash
`

type UpdateUserRoleParams struct {
	Role        UserRole `json:"role"`
	ID          string   `json:"id"`
	WorkspaceID string   `json:"workspace_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.Role, arg.ID, arg.WorkspaceID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}
