/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as OnboardingRouteImport } from "./routes/onboarding"
import { Route as DashboardRouteImport } from "./routes/_dashboard"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as InviteTokenRouteImport } from "./routes/invite.$token"
import { Route as DashboardWorkflowsRouteImport } from "./routes/_dashboard/workflows"
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard/settings"
import { Route as DashboardProfilesRouteImport } from "./routes/_dashboard/profiles"
import { Route as DashboardPipelineRouteImport } from "./routes/_dashboard/pipeline"
import { Route as DashboardMembersRouteImport } from "./routes/_dashboard/members"
import { Route as DashboardKnowledgeBaseRouteImport } from "./routes/_dashboard/knowledge-base"
import { Route as DashboardInboxRouteImport } from "./routes/_dashboard/inbox"
import { Route as DashboardBrowserSessionsRouteImport } from "./routes/_dashboard/browser-sessions"
import { Route as DashboardAnalyticsRouteImport } from "./routes/_dashboard/analytics"
import { Route as DashboardAlertsRouteImport } from "./routes/_dashboard/alerts"
import { Route as AuthSetupRouteImport } from "./routes/_auth/setup"
import { Route as AuthLoginRouteImport } from "./routes/_auth/login"
import { Route as DashboardAgentsIndexRouteImport } from "./routes/_dashboard/agents/index"
import { Route as DashboardAgentsAgentIdRouteImport } from "./routes/_dashboard/agents/$agentId"

const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowsRoute = DashboardWorkflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfilesRoute = DashboardProfilesRouteImport.update({
  id: "/profiles",
  path: "/profiles",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPipelineRoute = DashboardPipelineRouteImport.update({
  id: "/pipeline",
  path: "/pipeline",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: "/members",
  path: "/members",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeBaseRoute = DashboardKnowledgeBaseRouteImport.update({
  id: "/knowledge-base",
  path: "/knowledge-base",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: "/inbox",
  path: "/inbox",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrowserSessionsRoute =
  DashboardBrowserSessionsRouteImport.update({
    id: "/browser-sessions",
    path: "/browser-sessions",
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: "/alerts",
  path: "/alerts",
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: "/agents/",
  path: "/agents/",
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsAgentIdRoute = DashboardAgentsAgentIdRouteImport.update({
  id: "/agents/$agentId",
  path: "/agents/$agentId",
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/privacy": typeof PrivacyRoute
  "/login": typeof AuthLoginRoute
  "/setup": typeof AuthSetupRoute
  "/alerts": typeof DashboardAlertsRoute
  "/analytics": typeof DashboardAnalyticsRoute
  "/browser-sessions": typeof DashboardBrowserSessionsRoute
  "/inbox": typeof DashboardInboxRoute
  "/knowledge-base": typeof DashboardKnowledgeBaseRoute
  "/members": typeof DashboardMembersRoute
  "/pipeline": typeof DashboardPipelineRoute
  "/profiles": typeof DashboardProfilesRoute
  "/settings": typeof DashboardSettingsRoute
  "/workflows": typeof DashboardWorkflowsRoute
  "/invite/$token": typeof InviteTokenRoute
  "/agents/$agentId": typeof DashboardAgentsAgentIdRoute
  "/agents/": typeof DashboardAgentsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/onboarding": typeof OnboardingRoute
  "/privacy": typeof PrivacyRoute
  "/login": typeof AuthLoginRoute
  "/setup": typeof AuthSetupRoute
  "/alerts": typeof DashboardAlertsRoute
  "/analytics": typeof DashboardAnalyticsRoute
  "/browser-sessions": typeof DashboardBrowserSessionsRoute
  "/inbox": typeof DashboardInboxRoute
  "/knowledge-base": typeof DashboardKnowledgeBaseRoute
  "/members": typeof DashboardMembersRoute
  "/pipeline": typeof DashboardPipelineRoute
  "/profiles": typeof DashboardProfilesRoute
  "/settings": typeof DashboardSettingsRoute
  "/workflows": typeof DashboardWorkflowsRoute
  "/invite/$token": typeof InviteTokenRoute
  "/agents/$agentId": typeof DashboardAgentsAgentIdRoute
  "/agents": typeof DashboardAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_auth": typeof AuthRouteWithChildren
  "/_dashboard": typeof DashboardRouteWithChildren
  "/onboarding": typeof OnboardingRoute
  "/privacy": typeof PrivacyRoute
  "/_auth/login": typeof AuthLoginRoute
  "/_auth/setup": typeof AuthSetupRoute
  "/_dashboard/alerts": typeof DashboardAlertsRoute
  "/_dashboard/analytics": typeof DashboardAnalyticsRoute
  "/_dashboard/browser-sessions": typeof DashboardBrowserSessionsRoute
  "/_dashboard/inbox": typeof DashboardInboxRoute
  "/_dashboard/knowledge-base": typeof DashboardKnowledgeBaseRoute
  "/_dashboard/members": typeof DashboardMembersRoute
  "/_dashboard/pipeline": typeof DashboardPipelineRoute
  "/_dashboard/profiles": typeof DashboardProfilesRoute
  "/_dashboard/settings": typeof DashboardSettingsRoute
  "/_dashboard/workflows": typeof DashboardWorkflowsRoute
  "/invite/$token": typeof InviteTokenRoute
  "/_dashboard/agents/$agentId": typeof DashboardAgentsAgentIdRoute
  "/_dashboard/agents/": typeof DashboardAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/onboarding"
    | "/privacy"
    | "/login"
    | "/setup"
    | "/alerts"
    | "/analytics"
    | "/browser-sessions"
    | "/inbox"
    | "/knowledge-base"
    | "/members"
    | "/pipeline"
    | "/profiles"
    | "/settings"
    | "/workflows"
    | "/invite/$token"
    | "/agents/$agentId"
    | "/agents/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/onboarding"
    | "/privacy"
    | "/login"
    | "/setup"
    | "/alerts"
    | "/analytics"
    | "/browser-sessions"
    | "/inbox"
    | "/knowledge-base"
    | "/members"
    | "/pipeline"
    | "/profiles"
    | "/settings"
    | "/workflows"
    | "/invite/$token"
    | "/agents/$agentId"
    | "/agents"
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_dashboard"
    | "/onboarding"
    | "/privacy"
    | "/_auth/login"
    | "/_auth/setup"
    | "/_dashboard/alerts"
    | "/_dashboard/analytics"
    | "/_dashboard/browser-sessions"
    | "/_dashboard/inbox"
    | "/_dashboard/knowledge-base"
    | "/_dashboard/members"
    | "/_dashboard/pipeline"
    | "/_dashboard/profiles"
    | "/_dashboard/settings"
    | "/_dashboard/workflows"
    | "/invite/$token"
    | "/_dashboard/agents/$agentId"
    | "/_dashboard/agents/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding": {
      id: "/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard": {
      id: "/_dashboard"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite/$token": {
      id: "/invite/$token"
      path: "/invite/$token"
      fullPath: "/invite/$token"
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_dashboard/workflows": {
      id: "/_dashboard/workflows"
      path: "/workflows"
      fullPath: "/workflows"
      preLoaderRoute: typeof DashboardWorkflowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/settings": {
      id: "/_dashboard/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/profiles": {
      id: "/_dashboard/profiles"
      path: "/profiles"
      fullPath: "/profiles"
      preLoaderRoute: typeof DashboardProfilesRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/pipeline": {
      id: "/_dashboard/pipeline"
      path: "/pipeline"
      fullPath: "/pipeline"
      preLoaderRoute: typeof DashboardPipelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/members": {
      id: "/_dashboard/members"
      path: "/members"
      fullPath: "/members"
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/knowledge-base": {
      id: "/_dashboard/knowledge-base"
      path: "/knowledge-base"
      fullPath: "/knowledge-base"
      preLoaderRoute: typeof DashboardKnowledgeBaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/inbox": {
      id: "/_dashboard/inbox"
      path: "/inbox"
      fullPath: "/inbox"
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/browser-sessions": {
      id: "/_dashboard/browser-sessions"
      path: "/browser-sessions"
      fullPath: "/browser-sessions"
      preLoaderRoute: typeof DashboardBrowserSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/analytics": {
      id: "/_dashboard/analytics"
      path: "/analytics"
      fullPath: "/analytics"
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/alerts": {
      id: "/_dashboard/alerts"
      path: "/alerts"
      fullPath: "/alerts"
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_auth/setup": {
      id: "/_auth/setup"
      path: "/setup"
      fullPath: "/setup"
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/login": {
      id: "/_auth/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_dashboard/agents/": {
      id: "/_dashboard/agents/"
      path: "/agents"
      fullPath: "/agents/"
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    "/_dashboard/agents/$agentId": {
      id: "/_dashboard/agents/$agentId"
      path: "/agents/$agentId"
      fullPath: "/agents/$agentId"
      preLoaderRoute: typeof DashboardAgentsAgentIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBrowserSessionsRoute: typeof DashboardBrowserSessionsRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardKnowledgeBaseRoute: typeof DashboardKnowledgeBaseRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardPipelineRoute: typeof DashboardPipelineRoute
  DashboardProfilesRoute: typeof DashboardProfilesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWorkflowsRoute: typeof DashboardWorkflowsRoute
  DashboardAgentsAgentIdRoute: typeof DashboardAgentsAgentIdRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBrowserSessionsRoute: DashboardBrowserSessionsRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardKnowledgeBaseRoute: DashboardKnowledgeBaseRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardPipelineRoute: DashboardPipelineRoute,
  DashboardProfilesRoute: DashboardProfilesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWorkflowsRoute: DashboardWorkflowsRoute,
  DashboardAgentsAgentIdRoute: DashboardAgentsAgentIdRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
